// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IntentsColumns holds the columns for the "intents" table.
	IntentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// IntentsTable holds the schema information for the "intents" table.
	IntentsTable = &schema.Table{
		Name:       "intents",
		Columns:    IntentsColumns,
		PrimaryKey: []*schema.Column{IntentsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IntentsTable,
	}
)

func init() {
}
