// Code generated by ent, DO NOT EDIT.

package intentrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the intentrule type in the database.
	Label = "intent_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldIntentName holds the string denoting the intent_name field in the database.
	FieldIntentName = "intent_name"
	// FieldPatterns holds the string denoting the patterns field in the database.
	FieldPatterns = "patterns"
	// FieldMatchType holds the string denoting the match_type field in the database.
	FieldMatchType = "match_type"
	// FieldParams holds the string denoting the params field in the database.
	FieldParams = "params"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldConfidence holds the string denoting the confidence field in the database.
	FieldConfidence = "confidence"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the intentrule in the database.
	Table = "intent_rules"
)

// Columns holds all SQL columns for intentrule fields.
var Columns = []string{
	FieldID,
	FieldRuleID,
	FieldIntentName,
	FieldPatterns,
	FieldMatchType,
	FieldParams,
	FieldPriority,
	FieldConfidence,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RuleIDValidator is a validator for the "rule_id" field. It is called by the builders before save.
	RuleIDValidator func(string) error
	// IntentNameValidator is a validator for the "intent_name" field. It is called by the builders before save.
	IntentNameValidator func(string) error
	// DefaultMatchType holds the default value on creation for the "match_type" field.
	DefaultMatchType string
	// MatchTypeValidator is a validator for the "match_type" field. It is called by the builders before save.
	MatchTypeValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultConfidence holds the default value on creation for the "confidence" field.
	DefaultConfidence float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(uint64) error
)

// OrderOption defines the ordering options for the IntentRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// ByIntentName orders the results by the intent_name field.
func ByIntentName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntentName, opts...).ToFunc()
}

// ByMatchType orders the results by the match_type field.
func ByMatchType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMatchType, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByConfidence orders the results by the confidence field.
func ByConfidence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfidence, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
