// Code generated by ent, DO NOT EDIT.

package intentrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ecodeclub/ai-gateway-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldID, id))
}

// RuleID applies equality check predicate on the "rule_id" field. It's identical to RuleIDEQ.
func RuleID(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldRuleID, v))
}

// IntentName applies equality check predicate on the "intent_name" field. It's identical to IntentNameEQ.
func IntentName(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldIntentName, v))
}

// MatchType applies equality check predicate on the "match_type" field. It's identical to MatchTypeEQ.
func MatchType(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldMatchType, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldPriority, v))
}

// Confidence applies equality check predicate on the "confidence" field. It's identical to ConfidenceEQ.
func Confidence(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldConfidence, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// RuleIDEQ applies the EQ predicate on the "rule_id" field.
func RuleIDEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldRuleID, v))
}

// RuleIDNEQ applies the NEQ predicate on the "rule_id" field.
func RuleIDNEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldRuleID, v))
}

// RuleIDIn applies the In predicate on the "rule_id" field.
func RuleIDIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldRuleID, vs...))
}

// RuleIDNotIn applies the NotIn predicate on the "rule_id" field.
func RuleIDNotIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldRuleID, vs...))
}

// RuleIDGT applies the GT predicate on the "rule_id" field.
func RuleIDGT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldRuleID, v))
}

// RuleIDGTE applies the GTE predicate on the "rule_id" field.
func RuleIDGTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldRuleID, v))
}

// RuleIDLT applies the LT predicate on the "rule_id" field.
func RuleIDLT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldRuleID, v))
}

// RuleIDLTE applies the LTE predicate on the "rule_id" field.
func RuleIDLTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldRuleID, v))
}

// RuleIDContains applies the Contains predicate on the "rule_id" field.
func RuleIDContains(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContains(FieldRuleID, v))
}

// RuleIDHasPrefix applies the HasPrefix predicate on the "rule_id" field.
func RuleIDHasPrefix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasPrefix(FieldRuleID, v))
}

// RuleIDHasSuffix applies the HasSuffix predicate on the "rule_id" field.
func RuleIDHasSuffix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasSuffix(FieldRuleID, v))
}

// RuleIDEqualFold applies the EqualFold predicate on the "rule_id" field.
func RuleIDEqualFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEqualFold(FieldRuleID, v))
}

// RuleIDContainsFold applies the ContainsFold predicate on the "rule_id" field.
func RuleIDContainsFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContainsFold(FieldRuleID, v))
}

// IntentNameEQ applies the EQ predicate on the "intent_name" field.
func IntentNameEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldIntentName, v))
}

// IntentNameNEQ applies the NEQ predicate on the "intent_name" field.
func IntentNameNEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldIntentName, v))
}

// IntentNameIn applies the In predicate on the "intent_name" field.
func IntentNameIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldIntentName, vs...))
}

// IntentNameNotIn applies the NotIn predicate on the "intent_name" field.
func IntentNameNotIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldIntentName, vs...))
}

// IntentNameGT applies the GT predicate on the "intent_name" field.
func IntentNameGT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldIntentName, v))
}

// IntentNameGTE applies the GTE predicate on the "intent_name" field.
func IntentNameGTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldIntentName, v))
}

// IntentNameLT applies the LT predicate on the "intent_name" field.
func IntentNameLT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldIntentName, v))
}

// IntentNameLTE applies the LTE predicate on the "intent_name" field.
func IntentNameLTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldIntentName, v))
}

// IntentNameContains applies the Contains predicate on the "intent_name" field.
func IntentNameContains(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContains(FieldIntentName, v))
}

// IntentNameHasPrefix applies the HasPrefix predicate on the "intent_name" field.
func IntentNameHasPrefix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasPrefix(FieldIntentName, v))
}

// IntentNameHasSuffix applies the HasSuffix predicate on the "intent_name" field.
func IntentNameHasSuffix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasSuffix(FieldIntentName, v))
}

// IntentNameEqualFold applies the EqualFold predicate on the "intent_name" field.
func IntentNameEqualFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEqualFold(FieldIntentName, v))
}

// IntentNameContainsFold applies the ContainsFold predicate on the "intent_name" field.
func IntentNameContainsFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContainsFold(FieldIntentName, v))
}

// MatchTypeEQ applies the EQ predicate on the "match_type" field.
func MatchTypeEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldMatchType, v))
}

// MatchTypeNEQ applies the NEQ predicate on the "match_type" field.
func MatchTypeNEQ(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldMatchType, v))
}

// MatchTypeIn applies the In predicate on the "match_type" field.
func MatchTypeIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldMatchType, vs...))
}

// MatchTypeNotIn applies the NotIn predicate on the "match_type" field.
func MatchTypeNotIn(vs ...string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldMatchType, vs...))
}

// MatchTypeGT applies the GT predicate on the "match_type" field.
func MatchTypeGT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldMatchType, v))
}

// MatchTypeGTE applies the GTE predicate on the "match_type" field.
func MatchTypeGTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldMatchType, v))
}

// MatchTypeLT applies the LT predicate on the "match_type" field.
func MatchTypeLT(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldMatchType, v))
}

// MatchTypeLTE applies the LTE predicate on the "match_type" field.
func MatchTypeLTE(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldMatchType, v))
}

// MatchTypeContains applies the Contains predicate on the "match_type" field.
func MatchTypeContains(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContains(FieldMatchType, v))
}

// MatchTypeHasPrefix applies the HasPrefix predicate on the "match_type" field.
func MatchTypeHasPrefix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasPrefix(FieldMatchType, v))
}

// MatchTypeHasSuffix applies the HasSuffix predicate on the "match_type" field.
func MatchTypeHasSuffix(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldHasSuffix(FieldMatchType, v))
}

// MatchTypeEqualFold applies the EqualFold predicate on the "match_type" field.
func MatchTypeEqualFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEqualFold(FieldMatchType, v))
}

// MatchTypeContainsFold applies the ContainsFold predicate on the "match_type" field.
func MatchTypeContainsFold(v string) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldContainsFold(FieldMatchType, v))
}

// ParamsIsNil applies the IsNil predicate on the "params" field.
func ParamsIsNil() predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIsNull(FieldParams))
}

// ParamsNotNil applies the NotNil predicate on the "params" field.
func ParamsNotNil() predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotNull(FieldParams))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldPriority, v))
}

// ConfidenceEQ applies the EQ predicate on the "confidence" field.
func ConfidenceEQ(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldConfidence, v))
}

// ConfidenceNEQ applies the NEQ predicate on the "confidence" field.
func ConfidenceNEQ(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldConfidence, v))
}

// ConfidenceIn applies the In predicate on the "confidence" field.
func ConfidenceIn(vs ...float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldConfidence, vs...))
}

// ConfidenceNotIn applies the NotIn predicate on the "confidence" field.
func ConfidenceNotIn(vs ...float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldConfidence, vs...))
}

// ConfidenceGT applies the GT predicate on the "confidence" field.
func ConfidenceGT(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldConfidence, v))
}

// ConfidenceGTE applies the GTE predicate on the "confidence" field.
func ConfidenceGTE(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldConfidence, v))
}

// ConfidenceLT applies the LT predicate on the "confidence" field.
func ConfidenceLT(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldConfidence, v))
}

// ConfidenceLTE applies the LTE predicate on the "confidence" field.
func ConfidenceLTE(v float64) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldConfidence, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IntentRule {
	return predicate.IntentRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IntentRule) predicate.IntentRule {
	return predicate.IntentRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IntentRule) predicate.IntentRule {
	return predicate.IntentRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.IntentRule) predicate.IntentRule {
	return predicate.IntentRule(sql.NotPredicates(p))
}
