// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ecodeclub/ai-gateway-go/ent/intentrule"
)

// IntentRule is the model entity for the IntentRule schema.
type IntentRule struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID uint64 `json:"id,omitempty"`
	// 规则唯一ID
	RuleID string `json:"rule_id,omitempty"`
	// 意图名称
	IntentName string `json:"intent_name,omitempty"`
	// 匹配模式列表
	Patterns []string `json:"patterns,omitempty"`
	// exact/prefix/contains/regex
	MatchType string `json:"match_type,omitempty"`
	// 规则携带的默认参数
	Params map[string]string `json:"params,omitempty"`
	// 优先级, 越大越优先
	Priority int `json:"priority,omitempty"`
	// 该规则的固定置信度
	Confidence float64 `json:"confidence,omitempty"`
	// 1=启用 0=禁用
	Status int8 `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IntentRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case intentrule.FieldPatterns, intentrule.FieldParams:
			values[i] = new([]byte)
		case intentrule.FieldConfidence:
			values[i] = new(sql.NullFloat64)
		case intentrule.FieldID, intentrule.FieldPriority, intentrule.FieldStatus:
			values[i] = new(sql.NullInt64)
		case intentrule.FieldRuleID, intentrule.FieldIntentName, intentrule.FieldMatchType:
			values[i] = new(sql.NullString)
		case intentrule.FieldCreatedAt, intentrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IntentRule fields.
func (_m *IntentRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case intentrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case intentrule.FieldRuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rule_id", values[i])
			} else if value.Valid {
				_m.RuleID = value.String
			}
		case intentrule.FieldIntentName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field intent_name", values[i])
			} else if value.Valid {
				_m.IntentName = value.String
			}
		case intentrule.FieldPatterns:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field patterns", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Patterns); err != nil {
					return fmt.Errorf("unmarshal field patterns: %w", err)
				}
			}
		case intentrule.FieldMatchType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_type", values[i])
			} else if value.Valid {
				_m.MatchType = value.String
			}
		case intentrule.FieldParams:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Params); err != nil {
					return fmt.Errorf("unmarshal field params: %w", err)
				}
			}
		case intentrule.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case intentrule.FieldConfidence:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field confidence", values[i])
			} else if value.Valid {
				_m.Confidence = value.Float64
			}
		case intentrule.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case intentrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case intentrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IntentRule.
// This includes values selected through modifiers, order, etc.
func (_m *IntentRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this IntentRule.
// Note that you need to call IntentRule.Unwrap() before calling this method if this IntentRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *IntentRule) Update() *IntentRuleUpdateOne {
	return NewIntentRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the IntentRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *IntentRule) Unwrap() *IntentRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: IntentRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *IntentRule) String() string {
	var builder strings.Builder
	builder.WriteString("IntentRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rule_id=")
	builder.WriteString(_m.RuleID)
	builder.WriteString(", ")
	builder.WriteString("intent_name=")
	builder.WriteString(_m.IntentName)
	builder.WriteString(", ")
	builder.WriteString("patterns=")
	builder.WriteString(fmt.Sprintf("%v", _m.Patterns))
	builder.WriteString(", ")
	builder.WriteString("match_type=")
	builder.WriteString(_m.MatchType)
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(fmt.Sprintf("%v", _m.Params))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("confidence=")
	builder.WriteString(fmt.Sprintf("%v", _m.Confidence))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// IntentRules is a parsable slice of IntentRule.
type IntentRules []*IntentRule
