// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/ecodeclub/ai-gateway-go/ent/intentrule"
	"github.com/ecodeclub/ai-gateway-go/ent/predicate"
)

// IntentRuleUpdate is the builder for updating IntentRule entities.
type IntentRuleUpdate struct {
	config
	hooks    []Hook
	mutation *IntentRuleMutation
}

// Where appends a list predicates to the IntentRuleUpdate builder.
func (_u *IntentRuleUpdate) Where(ps ...predicate.IntentRule) *IntentRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRuleID sets the "rule_id" field.
func (_u *IntentRuleUpdate) SetRuleID(v string) *IntentRuleUpdate {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillableRuleID(v *string) *IntentRuleUpdate {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetIntentName sets the "intent_name" field.
func (_u *IntentRuleUpdate) SetIntentName(v string) *IntentRuleUpdate {
	_u.mutation.SetIntentName(v)
	return _u
}

// SetNillableIntentName sets the "intent_name" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillableIntentName(v *string) *IntentRuleUpdate {
	if v != nil {
		_u.SetIntentName(*v)
	}
	return _u
}

// SetPatterns sets the "patterns" field.
func (_u *IntentRuleUpdate) SetPatterns(v []string) *IntentRuleUpdate {
	_u.mutation.SetPatterns(v)
	return _u
}

// AppendPatterns appends value to the "patterns" field.
func (_u *IntentRuleUpdate) AppendPatterns(v []string) *IntentRuleUpdate {
	_u.mutation.AppendPatterns(v)
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *IntentRuleUpdate) SetMatchType(v string) *IntentRuleUpdate {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillableMatchType(v *string) *IntentRuleUpdate {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *IntentRuleUpdate) SetParams(v map[string]string) *IntentRuleUpdate {
	_u.mutation.SetParams(v)
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *IntentRuleUpdate) ClearParams() *IntentRuleUpdate {
	_u.mutation.ClearParams()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *IntentRuleUpdate) SetPriority(v int) *IntentRuleUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillablePriority(v *int) *IntentRuleUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *IntentRuleUpdate) AddPriority(v int) *IntentRuleUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *IntentRuleUpdate) SetConfidence(v float64) *IntentRuleUpdate {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillableConfidence(v *float64) *IntentRuleUpdate {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *IntentRuleUpdate) AddConfidence(v float64) *IntentRuleUpdate {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *IntentRuleUpdate) SetStatus(v int8) *IntentRuleUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IntentRuleUpdate) SetNillableStatus(v *int8) *IntentRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *IntentRuleUpdate) AddStatus(v int8) *IntentRuleUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntentRuleUpdate) SetUpdatedAt(v time.Time) *IntentRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the IntentRuleMutation object of the builder.
func (_u *IntentRuleUpdate) Mutation() *IntentRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IntentRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntentRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IntentRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntentRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntentRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intentrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntentRuleUpdate) check() error {
	if v, ok := _u.mutation.RuleID(); ok {
		if err := intentrule.RuleIDValidator(v); err != nil {
			return &ValidationError{Name: "rule_id", err: fmt.Errorf(`ent: validator failed for field "IntentRule.rule_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntentName(); ok {
		if err := intentrule.IntentNameValidator(v); err != nil {
			return &ValidationError{Name: "intent_name", err: fmt.Errorf(`ent: validator failed for field "IntentRule.intent_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := intentrule.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "IntentRule.match_type": %w`, err)}
		}
	}
	return nil
}

func (_u *IntentRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intentrule.Table, intentrule.Columns, sqlgraph.NewFieldSpec(intentrule.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(intentrule.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntentName(); ok {
		_spec.SetField(intentrule.FieldIntentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Patterns(); ok {
		_spec.SetField(intentrule.FieldPatterns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPatterns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intentrule.FieldPatterns, value)
		})
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(intentrule.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(intentrule.FieldParams, field.TypeJSON, value)
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(intentrule.FieldParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(intentrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(intentrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(intentrule.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(intentrule.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(intentrule.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(intentrule.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intentrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IntentRuleUpdateOne is the builder for updating a single IntentRule entity.
type IntentRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IntentRuleMutation
}

// SetRuleID sets the "rule_id" field.
func (_u *IntentRuleUpdateOne) SetRuleID(v string) *IntentRuleUpdateOne {
	_u.mutation.SetRuleID(v)
	return _u
}

// SetNillableRuleID sets the "rule_id" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillableRuleID(v *string) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetRuleID(*v)
	}
	return _u
}

// SetIntentName sets the "intent_name" field.
func (_u *IntentRuleUpdateOne) SetIntentName(v string) *IntentRuleUpdateOne {
	_u.mutation.SetIntentName(v)
	return _u
}

// SetNillableIntentName sets the "intent_name" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillableIntentName(v *string) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetIntentName(*v)
	}
	return _u
}

// SetPatterns sets the "patterns" field.
func (_u *IntentRuleUpdateOne) SetPatterns(v []string) *IntentRuleUpdateOne {
	_u.mutation.SetPatterns(v)
	return _u
}

// AppendPatterns appends value to the "patterns" field.
func (_u *IntentRuleUpdateOne) AppendPatterns(v []string) *IntentRuleUpdateOne {
	_u.mutation.AppendPatterns(v)
	return _u
}

// SetMatchType sets the "match_type" field.
func (_u *IntentRuleUpdateOne) SetMatchType(v string) *IntentRuleUpdateOne {
	_u.mutation.SetMatchType(v)
	return _u
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillableMatchType(v *string) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetMatchType(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *IntentRuleUpdateOne) SetParams(v map[string]string) *IntentRuleUpdateOne {
	_u.mutation.SetParams(v)
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *IntentRuleUpdateOne) ClearParams() *IntentRuleUpdateOne {
	_u.mutation.ClearParams()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *IntentRuleUpdateOne) SetPriority(v int) *IntentRuleUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillablePriority(v *int) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *IntentRuleUpdateOne) AddPriority(v int) *IntentRuleUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetConfidence sets the "confidence" field.
func (_u *IntentRuleUpdateOne) SetConfidence(v float64) *IntentRuleUpdateOne {
	_u.mutation.ResetConfidence()
	_u.mutation.SetConfidence(v)
	return _u
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillableConfidence(v *float64) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetConfidence(*v)
	}
	return _u
}

// AddConfidence adds value to the "confidence" field.
func (_u *IntentRuleUpdateOne) AddConfidence(v float64) *IntentRuleUpdateOne {
	_u.mutation.AddConfidence(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *IntentRuleUpdateOne) SetStatus(v int8) *IntentRuleUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IntentRuleUpdateOne) SetNillableStatus(v *int8) *IntentRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *IntentRuleUpdateOne) AddStatus(v int8) *IntentRuleUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *IntentRuleUpdateOne) SetUpdatedAt(v time.Time) *IntentRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the IntentRuleMutation object of the builder.
func (_u *IntentRuleUpdateOne) Mutation() *IntentRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the IntentRuleUpdate builder.
func (_u *IntentRuleUpdateOne) Where(ps ...predicate.IntentRule) *IntentRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IntentRuleUpdateOne) Select(field string, fields ...string) *IntentRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IntentRule entity.
func (_u *IntentRuleUpdateOne) Save(ctx context.Context) (*IntentRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IntentRuleUpdateOne) SaveX(ctx context.Context) *IntentRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IntentRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IntentRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *IntentRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := intentrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IntentRuleUpdateOne) check() error {
	if v, ok := _u.mutation.RuleID(); ok {
		if err := intentrule.RuleIDValidator(v); err != nil {
			return &ValidationError{Name: "rule_id", err: fmt.Errorf(`ent: validator failed for field "IntentRule.rule_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IntentName(); ok {
		if err := intentrule.IntentNameValidator(v); err != nil {
			return &ValidationError{Name: "intent_name", err: fmt.Errorf(`ent: validator failed for field "IntentRule.intent_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchType(); ok {
		if err := intentrule.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "IntentRule.match_type": %w`, err)}
		}
	}
	return nil
}

func (_u *IntentRuleUpdateOne) sqlSave(ctx context.Context) (_node *IntentRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(intentrule.Table, intentrule.Columns, sqlgraph.NewFieldSpec(intentrule.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IntentRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, intentrule.FieldID)
		for _, f := range fields {
			if !intentrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != intentrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RuleID(); ok {
		_spec.SetField(intentrule.FieldRuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.IntentName(); ok {
		_spec.SetField(intentrule.FieldIntentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Patterns(); ok {
		_spec.SetField(intentrule.FieldPatterns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPatterns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, intentrule.FieldPatterns, value)
		})
	}
	if value, ok := _u.mutation.MatchType(); ok {
		_spec.SetField(intentrule.FieldMatchType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(intentrule.FieldParams, field.TypeJSON, value)
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(intentrule.FieldParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(intentrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(intentrule.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Confidence(); ok {
		_spec.SetField(intentrule.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedConfidence(); ok {
		_spec.AddField(intentrule.FieldConfidence, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(intentrule.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(intentrule.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrule.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &IntentRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{intentrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
