// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ecodeclub/ai-gateway-go/ent/intentrule"
)

// IntentRuleCreate is the builder for creating a IntentRule entity.
type IntentRuleCreate struct {
	config
	mutation *IntentRuleMutation
	hooks    []Hook
}

// SetRuleID sets the "rule_id" field.
func (_c *IntentRuleCreate) SetRuleID(v string) *IntentRuleCreate {
	_c.mutation.SetRuleID(v)
	return _c
}

// SetIntentName sets the "intent_name" field.
func (_c *IntentRuleCreate) SetIntentName(v string) *IntentRuleCreate {
	_c.mutation.SetIntentName(v)
	return _c
}

// SetPatterns sets the "patterns" field.
func (_c *IntentRuleCreate) SetPatterns(v []string) *IntentRuleCreate {
	_c.mutation.SetPatterns(v)
	return _c
}

// SetMatchType sets the "match_type" field.
func (_c *IntentRuleCreate) SetMatchType(v string) *IntentRuleCreate {
	_c.mutation.SetMatchType(v)
	return _c
}

// SetNillableMatchType sets the "match_type" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillableMatchType(v *string) *IntentRuleCreate {
	if v != nil {
		_c.SetMatchType(*v)
	}
	return _c
}

// SetParams sets the "params" field.
func (_c *IntentRuleCreate) SetParams(v map[string]string) *IntentRuleCreate {
	_c.mutation.SetParams(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *IntentRuleCreate) SetPriority(v int) *IntentRuleCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillablePriority(v *int) *IntentRuleCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetConfidence sets the "confidence" field.
func (_c *IntentRuleCreate) SetConfidence(v float64) *IntentRuleCreate {
	_c.mutation.SetConfidence(v)
	return _c
}

// SetNillableConfidence sets the "confidence" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillableConfidence(v *float64) *IntentRuleCreate {
	if v != nil {
		_c.SetConfidence(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *IntentRuleCreate) SetStatus(v int8) *IntentRuleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillableStatus(v *int8) *IntentRuleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *IntentRuleCreate) SetCreatedAt(v time.Time) *IntentRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillableCreatedAt(v *time.Time) *IntentRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *IntentRuleCreate) SetUpdatedAt(v time.Time) *IntentRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *IntentRuleCreate) SetNillableUpdatedAt(v *time.Time) *IntentRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IntentRuleCreate) SetID(v uint64) *IntentRuleCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the IntentRuleMutation object of the builder.
func (_c *IntentRuleCreate) Mutation() *IntentRuleMutation {
	return _c.mutation
}

// Save creates the IntentRule in the database.
func (_c *IntentRuleCreate) Save(ctx context.Context) (*IntentRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IntentRuleCreate) SaveX(ctx context.Context) *IntentRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntentRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntentRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IntentRuleCreate) defaults() {
	if _, ok := _c.mutation.MatchType(); !ok {
		v := intentrule.DefaultMatchType
		_c.mutation.SetMatchType(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := intentrule.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		v := intentrule.DefaultConfidence
		_c.mutation.SetConfidence(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := intentrule.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := intentrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := intentrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *IntentRuleCreate) check() error {
	if _, ok := _c.mutation.RuleID(); !ok {
		return &ValidationError{Name: "rule_id", err: errors.New(`ent: missing required field "IntentRule.rule_id"`)}
	}
	if v, ok := _c.mutation.RuleID(); ok {
		if err := intentrule.RuleIDValidator(v); err != nil {
			return &ValidationError{Name: "rule_id", err: fmt.Errorf(`ent: validator failed for field "IntentRule.rule_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IntentName(); !ok {
		return &ValidationError{Name: "intent_name", err: errors.New(`ent: missing required field "IntentRule.intent_name"`)}
	}
	if v, ok := _c.mutation.IntentName(); ok {
		if err := intentrule.IntentNameValidator(v); err != nil {
			return &ValidationError{Name: "intent_name", err: fmt.Errorf(`ent: validator failed for field "IntentRule.intent_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Patterns(); !ok {
		return &ValidationError{Name: "patterns", err: errors.New(`ent: missing required field "IntentRule.patterns"`)}
	}
	if _, ok := _c.mutation.MatchType(); !ok {
		return &ValidationError{Name: "match_type", err: errors.New(`ent: missing required field "IntentRule.match_type"`)}
	}
	if v, ok := _c.mutation.MatchType(); ok {
		if err := intentrule.MatchTypeValidator(v); err != nil {
			return &ValidationError{Name: "match_type", err: fmt.Errorf(`ent: validator failed for field "IntentRule.match_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "IntentRule.priority"`)}
	}
	if _, ok := _c.mutation.Confidence(); !ok {
		return &ValidationError{Name: "confidence", err: errors.New(`ent: missing required field "IntentRule.confidence"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IntentRule.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "IntentRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "IntentRule.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := intentrule.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "IntentRule.id": %w`, err)}
		}
	}
	return nil
}

func (_c *IntentRuleCreate) sqlSave(ctx context.Context) (*IntentRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IntentRuleCreate) createSpec() (*IntentRule, *sqlgraph.CreateSpec) {
	var (
		_node = &IntentRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(intentrule.Table, sqlgraph.NewFieldSpec(intentrule.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.RuleID(); ok {
		_spec.SetField(intentrule.FieldRuleID, field.TypeString, value)
		_node.RuleID = value
	}
	if value, ok := _c.mutation.IntentName(); ok {
		_spec.SetField(intentrule.FieldIntentName, field.TypeString, value)
		_node.IntentName = value
	}
	if value, ok := _c.mutation.Patterns(); ok {
		_spec.SetField(intentrule.FieldPatterns, field.TypeJSON, value)
		_node.Patterns = value
	}
	if value, ok := _c.mutation.MatchType(); ok {
		_spec.SetField(intentrule.FieldMatchType, field.TypeString, value)
		_node.MatchType = value
	}
	if value, ok := _c.mutation.Params(); ok {
		_spec.SetField(intentrule.FieldParams, field.TypeJSON, value)
		_node.Params = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(intentrule.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Confidence(); ok {
		_spec.SetField(intentrule.FieldConfidence, field.TypeFloat64, value)
		_node.Confidence = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(intentrule.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(intentrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(intentrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// IntentRuleCreateBulk is the builder for creating many IntentRule entities in bulk.
type IntentRuleCreateBulk struct {
	config
	err      error
	builders []*IntentRuleCreate
}

// Save creates the IntentRule entities in the database.
func (_c *IntentRuleCreateBulk) Save(ctx context.Context) ([]*IntentRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IntentRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IntentRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IntentRuleCreateBulk) SaveX(ctx context.Context) []*IntentRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IntentRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IntentRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
