// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// IntentRule is the predicate function for intentrule builders.
type IntentRule func(*sql.Selector)
